# 应用名称
name: temp
# 应用描述
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 应用版本
version: 1.0.0+1
# Dart 运行环境区间
environment:
  sdk: ">=2.7.0 <3.0.0"
  # 限制flutterSDK版本
  # flutter: "1.22.0"
# Flutter 依赖库
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  #状态管理
  provider: ^5.0.0
  #Flutter工具类库 flustars
  flustars: ^2.0.1
  sp_util: ^2.0.3
  #国际化
  flutter_localizations:
    sdk: flutter
  #路由管理
  fluro: ^2.0.3
  #GetX 是 Flutter 上的一个轻量且强大的解决方案：高性能的状态管理、智能的依赖注入和便捷的路由管理。
  get: ^4.1.4
  #通过事件总线来触发事件和监听事件
  #事件总线，是一种广播机制，遵循发布-订阅关系，发布者和订阅者之间不需要有父子关系。
  #在应用不需要大量的共享数据时,可以使用Event Bus来共享状态
  event_bus: ^2.0.0
  #
  #权限授权请求 https://github.com/Baseflow/flutter-permission-handler
  #状态管理
  scoped_model: ^2.0.0-nullsafety.0
  #状态管理
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  #状态管理
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  rxdart: ^0.26.0
  http: ^0.13.1
  #状态管理
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  #轮播
  # flutter_swiper : ^1.1.6
  flutter_swiper_null_safety: ^1.0.0
  #网络
  dio: ^4.0.0
  #Json解析
  json_annotation: ^4.0.1
  #网络监测
  connectivity: ^3.0.3
  #数据存储
  sqflite: ^2.0.0+3
  #文件路径
  path_provider: ^2.0.1
  shared_preferences_web: ^2.0.0
  #屏幕适配
  flutter_screenutil: ^5.0.0
  #UI组件库
  getwidget: ^2.0.1-nullsafety.4
  #打印工具
  logger: ^1.0.0
  #一台设备上查看不同分辨率设备上UI的效果工具
  # device_preview: ^0.7.1
  #官方的webview(基于iOS和安卓原生)
  webview_flutter: ^2.0.4
  flutter_inappwebview: ^5.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  #国际化工具
flutter_intl:
  enabled: true
